### PR TITLE
Inference mode and TF compatibility

### LINKED ISSUE #12: Using the Chatbot
Hi there,

I trained the data for a few days and now the samples are returning good results to the predefined "Happy Birthday" and "Trump" requests.

Great job by you. Thanks so far.

Do you already have a small python program for using the chatbot? If I write a message, the chatbot should return a single answer.

Thanks
Chris

### PR DESCRIPTION
**Pull request by pskrunner14**
* Moved Inference code to a function.
* Added optional arguments including running script in inference mode [usage `python main.py --help`].
* Added `tqdm` progress bar for info while training.
* Made the code compatible with TF v1.10.0 and TL v1.10.1.
* Changed `tf.contrib.rnn.BasicLSTMCell` to `tf.nn.rnn_cell.LSTMCell` since the former is deprecated.
* Moved `session config` to global scope.
* Refactored code into relevant functions and reordered them so that the higher-level ones appear earlier in the code.
* Renamed script to `main.py` for ease of use.
* Updated `README` to add training and inference usage commands.
* Added `requirements.txt` file.
* Changed `n.npz` to `model.npz` since it is more standard.

Note: Fixes #12 and #15

### CODE REVIEW

**Comment by pskrunner14** [comment]
@zsdonghao kindly resolve the file rename conflict and review PR. Thanks.

**Comment by zsdonghao** [comment]
Could you resolve the conflicts and then the PR is ready to merge to me.

**Comment by pskrunner14** [comment]
@zsdonghao all done :)

**Comment by pskrunner14** [comment]
@zsdonghao ready to merge.

**Pull request merged**
